# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: chimel
# "service" is the name of this project. This will also be added to your AWS resource names.
service: foodiary-api

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs22.x
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  environment: ${file(./sls/config/env.yml)}
  iam:
    role: ${file(./sls/config/role.yml)}
  httpApi:
    authorizers:
      CognitoAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: !GetAtt UserPool.ProviderURL
        audience:
          - !Ref UserPoolClient

custom:
  cognito:
    PoolName: ${self:service}-${self:provider.stage}-UserPool

package:
  individually: true

build:
  esbuild:
    configFile: ./esbuild.config.mjs

functions:
  - ${file(./sls/functions/auth.yml)}
  - ${file(./sls/functions/meals.yml)}

resources:
  - ${file(./sls/resources/userPool.yml)}
  - ${file(./sls/resources/mainTable.yml)}
